# Python CircleCI 2.1 configuration file
# for mets-mods2teiHeader
#
# Check https://circleci.com/docs/2.1/language-python/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.5
jobs:
  build:
    docker:
      - image: python:3.6
    working_directory: ~/repo
    steps:
      - checkout
      - run: pip install -r requirements-test.txt
      - run: pip install .
      - run: make coverage
      - codecov/upload
